### ISSUE TITLE
Start Problems since v4 

### ISSUE THREAD

**Issue by peppoonline** [zSeriesGuy/Tautulli#18]
OS: Server 2016
Python: 3.7x

"C:\Users\admin\AppData\Local\Programs\Python\Python37>python.exe C:\Users\admin\Downloads\Tautulli-4.0.01\Tautulli.py
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\Tautulli-4.0.01\Tautulli.py", line 32, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'"

What did I do wrong? Can you point me in the right direction? :)

**Comment by zSeriesGuy** [comment]
@peppoonline 
Did you see the installation instructions in the changelog?
https://github.com/zSeriesGuy/Tautulli/blob/master/CHANGELOG.md

Did you set up a python3 venv?

I wrote those instructions in the changelog with Linux in mind. I didn't really try it on Windows since Pycharm created the virtual environment.

**Comment by zSeriesGuy** [comment]
Try this:

In command window:

- CD to directory where you unzipped Tautulli
- python -m venv .\
- .\scripts\activate
- python -m pip install --upgrade --force-reinstall pip setuptools
- python -m pip install pip-tools
- pip3 install -r requirements.txt
- .\scripts\python Tautulli.py

**Comment by peppoonline** [comment]
Hey mate, your commands worked perfectly fine - thanks a lot!!!

**Comment by zSeriesGuy** [comment]
Glad it worked.
