### ISSUE TITLE
Support multiple Plex accounts

### ISSUE THREAD

**Issue by henrikx** [zSeriesGuy/Tautulli#32]
I have multiple Plex servers running on different Plex accounts. Would it be possible to authenticate different Plex users for access to different servers?

**Comment by zSeriesGuy** [comment]
Not at this time. Currently, this version of Tautulli only supports one owner Plex account.

**Comment by henrikx** [comment]
@zSeriesGuy That's a shame considering you need multiple accounts if you have more than 100 users...

**Comment by zSeriesGuy** [comment]
@henrikx  I'm not ruling it out. The problem is that the changes in this fork were not and will not be incorporated into the original Tautulli as I had hoped. So over time, there will be more disjoint between functions that get incorporated into the original Tautulli and this one unless I duplicate them...which was not my intent. One example is the changes to get the GeoDatabase function to work.

**Comment by henrikx** [comment]
I understand. 

Thank you.

**Comment by zSeriesGuy** [comment]
@henrikx 
I just published a new branch (MultiAccounts) that will give you multiple Plex.TV account capability. 
**This is BETA code.** 
So be sure to back up you tautulli database and config before switching to this branch.

If you find any problems, please open a new issue here.

**Comment by henrikx** [comment]
Works great so far!

Thanks a ton for your hard work.

**Comment by zSeriesGuy** [comment]
Thank you for the feedback. Much appreciated.

**Comment by zSeriesGuy** [comment]
If you were running multiple instances of my version of Tautulli, you can upgrade them and then import them into a single instance.
