### ISSUE TITLE
rclone

### ISSUE THREAD

**Issue by Tchuch0** [zSeriesGuy/Tautulli#34]
First let me say that it is an amazing work for multi server management :-) 

Quick question about rclone, it should active after "enable rclone mount monitoring" and going on the gear on one or all servers correct?

I've tried the stable and beta versions and on none appears any fields about rclone and after the option is enabled it just keeps getting unticked. tried it on windows and centOS vm

Best regards,

**Comment by zSeriesGuy** [comment]
After you enable rclone mount monitoring, are you clicking Save? This should enable the rclone monitoring settings on the servers when you then click on the gear for the server. When you click on the gear for the server and scroll all the way to the bottom of the server configuration modal, is there a Test Rclone Monitoring button?

**Comment by Tchuch0** [comment]
Hi @zSeriesGuy and thanks for the quick reply.

i'm saving but saving provides error and upon going to the gear no new options are available.

**Comment by zSeriesGuy** [comment]
Verify that the owner/group of config.ini and tautulli.db are the userid that you are running Tautulli under. Also check your tautulli log and see if there are any errors in the log.

**Comment by Tchuch0** [comment]
will test it and report back later on since i dont have the vm with me at the moment

**Comment by zSeriesGuy** [comment]
I just pushed an update that should fix this. Don't know how I missed it when I was testing V4.1.00. Dumb error on my part. 
Let me know if this works for you.

**Comment by Tchuch0** [comment]
Hello @zSeriesGuy , with the new update it does save the option to monitor and now i have settings to test the rclone mount. Just need to figure how to get each server to each client ID/remote :-)

**Comment by zSeriesGuy** [comment]
In your rclone mount statement, add --rc, --rc-user, and --rc--pass. You might also consider --rc-addr and use a different port for the rclone rc commands for improved security,  and --rc-cert, --rc-key for SSL support. But it is not required.
Specify that user, password, and port  in the Tautulli rclone Monitoring Settings.
The Mount Directory is the directory where rclone has mounted your drive.
Temp Directory is just a temporary directory where the rclone monitoring copies the Test Filename to in order to verify that the mount is working.
I created a one line file in the root of my plex directory on gdrive called testfile.txt. Don't need to copy a multi-GB file to verify rclone is functioning. So something small. For the temp directory, I use /dev/shm or /tmp.

Is this the info you needed? I'm not sure what you meant.
I probably should write a wiki page for this. :)

**Comment by Tchuch0** [comment]
All working fine :-)

Problem was (and is) that i have installed this on a VM on a load balance enviroment so went its "pinging" via isp 1 all rclone from that end are online, when its "pinging" via isp 2 all rclones from that end are online.

Will have to see what can be done on my end.

Another bug to be closed 👍
