### ISSUE TITLE
an update please

### ISSUE THREAD

**Issue by pazport** [zSeriesGuy/Tautulli#46]
hello mate, 
1st of ver well done.i love using this. i have a few plex apps. and feels great to get rid of the other tautulli and just using 1 :).

2nd could you  update this to the latest version of original tautulli. this tautulli is missing some features that i like in the original tautulli. 

3rd of. any chance you could make it so we can add our own ip/host for the plex instances. because it is grabbing plex container ip.i do prefer to use host name of the app. when on local machine.

**Comment by zSeriesGuy** [comment]
Thank you.

2) When I wrote this fork, the intent was to get it incorporated into the original Tautulli. Unfortunately, I was new to this type of development and the changes were way too many for them to accept. So they chose not to incorporate my changes.
The changes were massive. I thought about incorporating their changes into my fork. But it would be very difficult due to the volume of changes in my fork and where their changes are. So I won't be doing that.
What features from the original are you most interested in?

3) When I wrote this fork, the intent was to autodiscover owned plex servers. So I saw no need to be able to override the ip/host address. But I will consider it.

**Comment by pazport** [comment]
well it's like now. 2 of my plex instances have  updated. and tautulli says it can't connect to them. due to there ip as changed. so i have had to refresh the ip of those plex instances. for tautulli to pick them up. otherwise i will need to put plex instances on a dedicated ip. so when it restarts or updates. the ip doesn't change

**Comment by burnbrighter** [comment]
Love what you are doing.  Thank you for working on this.  Please keep up your good work. We definitely appreciate your efforts.
